### ISSUE TITLE
DOM not removed on HotspotDOM.destroy()

### ISSUE THREAD

**Issue by HeinrichKuhlmann** [gopro/forgejs#122]
Hi,
when switching between scenes the DOM from Hotspot dom is not removed:
https://releases.forgejs.org/latest/doc/jsdoc/hotspots_HotspotDOM.js.html#line380

whereas it is removed in the HotspotDOM.hide() function:
https://releases.forgejs.org/latest/doc/jsdoc/hotspots_HotspotDOM.js.html#line348

This creates the problem, that the DOM remains stay on the screen when scenes are switched.

best regards,
Heinrich

**Comment by bbaudel-gpsw** [comment]
Yes. It's an internal issue. On remove but also on creation with a multiple scene project.
Thanks for the report!

**Comment by aberthet-gpsw** [comment]
@HeinrichKuhlmann it is now resolved, if you build a new build from the sources, this issue shouldn't be here anymore
