### ISSUE TITLE
Use of WebVR polyfill with WebVR button on Androd results in black screen

### ISSUE THREAD

**Issue by Jickelsen** [gopro/forgejs#60]
#### Description of the problem

When hitting the WebVR button as detailed in http://forgejs.org/tutorials/basics/how-to-webvr, instead of showing cardboard instructions then a stereo view of the scene, the cardboard instructions are shown but followed by a black screen

##### ForgeJS version

0.9.2

##### Browser

- [x] Chrome 47 and 57
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android 5.0 and 6.0
- [ ] iOS

#### How to reproduce the problem

- Step 1
Clone https://github.com/Jickelsen/webvr-polyfill-forgejs-issue-example.git (uses only assets from 0.9.2 release, plugins from 0.9.2 release, plus webvr-polyfill-0.9.26)
- Step 2
Run with a https-supporting web server such as Budo
`budo --live --verbose --port 3000 --ssl --cors -wg '**/*.{html,css,json}'`
- Step 3
Open url using https with Chrome on Android
- Step 4
Hit WebVR button

**Comment by aberthet-gpsw** [comment]
We haven't released a version compatible with the polyfill, so you need to use the `webvr-polyfill` branch of this repo and build a version on it. You can find the build here :
[forge.min.js.zip](https://github.com/gopro/forgejs/files/961003/forge.min.js.zip)

The tutorial is missing this point, sorry about that, we'll be updating it.

**Comment by Jickelsen** [comment]
@aberthet-gpsw Thank you, with that version everything seems to work as expected. I guess the remaining issue to solve is to retain native support. WIth Chromium and Vive I get `Error: No VR hardware found`, but from the commit messages in the WebVR branch it seems you are aware of this.

**Comment by aberthet-gpsw** [comment]
Yes that's the inconvenience for now. Working to find a proper solution !
